### ISSUE TITLE
Unexpected server response (426) when using WebSocket

### ISSUE THREAD

**Issue by jbargu** [BTCChina/dax-trade-sdk-js#1]
When trying to use the provided code for accessing the order book:

```
const WebSocket = require('ws')
const uuidv4 = require('uuid/v4')

const ws = new WebSocket('wss://api-dax.btcc.com/ws/pub')

ws.on('open', () => {
  ws.send(JSON.stringify({
    MsgType: "QuoteRequest",
    CRID: uuidv4(),
    Symbol: "ETC_BTC",
    QuoteType: 2,
  }))
})

ws.on('message', (data) => {
  // Do something with GlobalTicker, OrderBook and ExecTradeBase
  console.log(data)
  ws.close() // Or remove this line to listen increment trade
})
```
I get the following error:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (426)
    at ClientRequest._req.on (~/workspace/btcc-node/node_modules/ws/lib/WebSocket.js:656:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
```

Note that this worked flawlessly the previous week and I haven't changed anything. Have you changed something on the server side?

**Comment by zcong1993** [comment]
ws url changed to `wss://ws-dax.btcc.com/ws/pub`

**Comment by knarfytrebil** [comment]
@jbargu Hello, Grabnar sorry we changed the address of the websocket.
Please use: `wss://ws-dax.btcc.com/ws/pub`
If it works fine with you, we can close this issue.
Cheers !

**Comment by jbargu** [comment]
Thank you very much for your swift answers. I opened MR #2  that updates the URL for anyone else that may encounter the issue.
